#version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: urbanclean-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/urbanclean.db:/app/urbanclean.db
    environment:
      - PORT=5000
      - DB_PATH=./urbanclean.db
      - UPLOAD_DIR=./uploads
    networks:
      - urbanclean-network

  frontend:
    build:
      context: ./frontend
    container_name: urbanclean-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - urbanclean-network

networks:
  urbanclean-network:
    driver: bridge
